name: Update status badge
on:
  push: {branches: [main]}
  release: {types: [published, prereleased]}
  workflow_dispatch: {}
permissions: {contents: write}
jobs:
  badge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Compute status
        env:
          EVENT_NAME: ${{ github.event_name }}
          PRERELEASE: ${{ github.event.release.prerelease }}
        run: |
          STATUS="work in process"; COLOR="yellow"
          if [ "$EVENT_NAME" = "release" ]; then
            if [ "$PRERELEASE" = "true" ]; then STATUS="beta"; COLOR="orange"
            else STATUS="stable"; COLOR="brightgreen"; fi
          fi
          printf '{ "schemaVersion":1,"label":"status","message":"%s","color":"%s","cacheSeconds":300 }\n' "$STATUS" "$COLOR" \
            > .github/status.json
      - name: Commit
        run: |
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git add .github/status.json
          git commit -m "chore: update status badge -> $(jq -r .message .github/status.json)" || exit 0
          git push